#!/usr/bin/env bash
# @file sync.sh
# Simple watch file changes and sync to external drive
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && {
    export PS4='+($(basename ${BASH_SOURCE[0]}):${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -x
}
set -eou pipefail

# Defaults assume sync of home directory to external Lacie drive
SOURCE_DIR="${1:-$HOME/}"
TARGET_DIR="${2:-/Volumes/Lacie/$HOSTNAME/}"

sync_local() {
    [ -d "$TARGET_DIR" ] || mkdir -p "$TARGET_DIR"
    
    # rsync flags used:
    # -g preserve group
    # -l copy symlinks as symlinks
    # -o preserve owner
    # -p preserve permissions
    # -t preserve times
    # -r recursive
    # -u skip files that are newer on the receiver
    # -n dry run
    # -c skip based on checksum, not mod-time & size
    # --delete delete extraneous files from dest dirs
    # --progress show progress during transfer

    # rsync -gloptrunc --delete --progress "$SOURCE_DIR" "$TARGET_DIR"
    rsync -gloptruc --delete --progress "$SOURCE_DIR" "$TARGET_DIR"
}

sync_local