#!/usr/bin/env bash
# @file xw.sh
# Find a synonym for a clue using the danword.com crossword solver
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && {
    export PS4='+($(basename ${BASH_SOURCE[0]}):${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -x
}
set -eou pipefail

XW_SOLVER_SERVICE="https://www.danword.com/crossword"
CLUE="$1"

fetch_soln() {
    local clue="$1"
    clue="${clue// /_}"
    open "$XW_SOLVER_SERVICE/$clue"
}

[ "$1" ] || {
    echo "Usage: $0 <clue>"
    exit 1
}

fetch_soln "$CLUE"