#!/usr/bin/env bash
# @file test_install
# Test install for Linux at least. No easy way to test in a macOS image
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

CONTAINER_NAME='test-install'

stand_up() {
	docker run -td --name "$CONTAINER_NAME" \
		--rm ubuntu:18.04
    docker cp "install.sh" "$CONTAINER_NAME":/
	docker exec -it "$CONTAINER_NAME" "/install.sh"
}

provide_shell() {
	docker exec -it "$CONTAINER_NAME" /bin/bash 
}

tear_down() {
	docker stop "$CONTAINER_NAME"
}

main() {
	stand_up
	provide_shell
	tear_down
}

main "$@"